name: "Knative Service Deploy"
description: "Create and manage Knative Services"
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  service_name:
    description: "The Knative Service Name"
    required: true
  namespace:
    description: "The Kubernetes Namespace to deploy to. Defaults to current context's namespace."
    required: false
  command:
    description: "The Knative service command, accepted commands are create, update, apply and delete"
    required: false
    default: "create"
  container_image:
    description: "The Knative Service Image"
    required: true
  kn_extra_args:
    description: "Any extra arguments to append to the kn <command>"
    required: false
  registry_user:
    description: "The registry user to use to create the image pull secret"
    required: false
  registry_password:
    description: "The registry user password"
    required: false
  force_create:
    description: |
      "Pass --force to kn create. If the service already exists,
      the service will be replaced, instead of kn create failing.
      This input has no effect if command is not create"
    required: false
    default: "false"
outputs:
  service_url:
    description: "The Knative Service URL"
runs:
  using: "docker"
  image: "Dockerfile"
