= Knative Service Deploy

GitHub Action to deploy https://kn.dev[Knative Service] using https://github.com/knative/client[Knative Client].

== Pre-requisites

Kubernetes Cluster with Knative, if you dont have an OpenShift cluster see https://try.openshift.com[try.openshift.com] or try our new https://developers.redhat.com/developer-sandbox[Developer Sandbox]

== Parameters

The action has the following parameters:

=== Inputs
[cols="1,2,1", options="header"]
|===
| Name | Description | Default
| service_name[red]^*^ | The Knative Service Name |
| service_namespace | The Kubernetes Namespace to deploy to. Defaults to current context's namespace |
| service_operation | The `kn` service operation *create*, *update*, *delete* etc., | create
| container_image[red]^*^ | The container image to use for service |
| service_params | The extra service parameters to pass to the service |
| registry_user |The registry user to use to create image pull secret. Required if image registry is private| 
| registry_password | The registry user password or token. Required if image registry is private | 
|===
==== Marked [red]^*^ are required attributes

=== Outputs
[cols="1,2", options="header"]
|===
| Name | Description
| service_url | Knative Service URL of the service created
|===

[NOTE]
====
When username and password is provided to pull the image, then the action will create a Kubernetes Secret of type `docker-registry` with the `docker-username` to be `registry_user` and `docker-password` to be `registry_password`. The `docker-server` value will be the first part of the `container_image` value.
====

== How to add to your action

- Create the required https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets[GitHub Secrets] in your GitHub repository:

- Container registry access e.g quay.io where you push built images.

For GitHub Container registry create the following secret and add to your repository:

`GHCR_PAT` - The https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token[GithHub PAT] to allow pushing built image into GitHub Container registry .

If you are using other Container registries you might need to add extra secrets to your repository typically for your registry username and password.

As OpenShift is used as the Kubernetes platform in the example, you can use the https://github.com/redhat-actions/oc-login[oc-login action],to login into the OpenShift cluster to perform `kn` actions.

[source,yaml]
----
# Login into the OpenShift cluster with your OpenShift username 
# and password
- name: Login into OpenShift Cluster
  id: oc_login
  uses: redhat-actions/oc-login@v1
  with:
    openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
    openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
    insecure_skip_tls_verify: true
    namespace: ${{ env.NAMESPACE }}

# With successful login in previous step, do the kn action
- name: Knative Service Deploy
  id: kn_service_deploy
  uses: redhat-actions/kn-service-deploy@v1
  with: 
    service_name: fruits-app
    container_image: "${{ steps.push-tag-to-quay.outputs.registry-path }}"
----

== Passing extra service arguments

The service action provides basic options such namespace, service name, image and operation to be configured. There might be cases where you might want to pass extra arguments to the `kn service <command>`, in those cases you can use `service_params` as shown:

Consider an example that you want to add `--max-scale=5` and `--min-scale=1`, then your action snippet will be:

[source,yaml]
----
- name: Knative Service Deploy
  id: kn_service_deploy
  uses: redhat-actions/kn-service-deploy@v1
  with: 
    service_name: fruits-app
    container_image: "${{ steps.push-tag-to-quay.outputs.registry-path }}"
    service_params: >
      --max-scale=5
      --min-scale=1
----

For a complete example see ./.github/workflows/example.yml[the example workflow].
